#include "rvaic.h"

#include <assert.h>
#include <string.h>

static int copy_run(void *user, const rvaic_tensor_t *inputs, rvaic_tensor_t *outputs)
{
    (void)user;
    outputs[0] = inputs[0];
    return 0;
}

static void done(void *user_data, int status)
{
    int *seen = (int *)user_data;
    *seen = status == 0 ? 1 : -1;
}

static int backend_resets;

static int backend_reset(void)
{
    backend_resets++;
    return 0;
}

int main(void)
{
    unsigned char pool[96];
    int data[4] = {1, 2, 3, 4};
    int callback_seen = 0;
    rvaic_tensor_t input;
    rvaic_tensor_t output;
    rvaic_job_t job;
    rvaic_job_t dep_job;
    rvaic_job_t low_job;
    rvaic_job_t high_job;
    rvaic_job_t npu_blocked_job;
    rvaic_job_t cpu_unblocked_job;
    rvaic_job_t npu_fallback_job;
    rvaic_job_t ready_job;
    rvaic_fence_t fence;
    rvaic_fence_t dep_fence;
    rvaic_fence_t low_fence;
    rvaic_fence_t high_fence;
    rvaic_fence_t ready_fence;
    rvaic_plan_t plans[2];
    rvaic_backend_ops_t backend;
    rvaic_arena_reservation_t reservation_a;
    rvaic_arena_reservation_t reservation_b;
    rvaic_arena_reservation_t reservation_fixed;
    rvaic_service_stats_t service_stats;
    rvaic_backend_queue_state_t queue_state;
    rvaic_admission_entry_t admission[2];
    rvaic_plan_admission_result_t plan_admission;
    rvaic_session_t *session;
    const rvaic_session_t *parallel_session;
    const rvaic_session_t *serial_session;
    const rvaic_session_t *session2;
    rvaic_model_t model;
    rvaic_model_t other_model;
    rvaic_model_t bad_model;
    rvaic_model_t mismatch_model;
    rvaic_model_t replacement_model;

    memset(&input, 0, sizeof(input));
    memset(&output, 0, sizeof(output));
    memset(&job, 0, sizeof(job));
    memset(&dep_job, 0, sizeof(dep_job));
    memset(&low_job, 0, sizeof(low_job));
    memset(&high_job, 0, sizeof(high_job));
    memset(&npu_blocked_job, 0, sizeof(npu_blocked_job));
    memset(&cpu_unblocked_job, 0, sizeof(cpu_unblocked_job));
    memset(&npu_fallback_job, 0, sizeof(npu_fallback_job));
    memset(&ready_job, 0, sizeof(ready_job));
    memset(&fence, 0, sizeof(fence));
    memset(&dep_fence, 0, sizeof(dep_fence));
    memset(&low_fence, 0, sizeof(low_fence));
    memset(&high_fence, 0, sizeof(high_fence));
    memset(&ready_fence, 0, sizeof(ready_fence));
    memset(plans, 0, sizeof(plans));
    memset(&backend, 0, sizeof(backend));
    memset(&reservation_a, 0, sizeof(reservation_a));
    memset(&reservation_b, 0, sizeof(reservation_b));
    memset(&reservation_fixed, 0, sizeof(reservation_fixed));
    memset(&service_stats, 0, sizeof(service_stats));
    memset(&queue_state, 0, sizeof(queue_state));
    memset(admission, 0, sizeof(admission));
    memset(&plan_admission, 0, sizeof(plan_admission));
    memset(&model, 0, sizeof(model));
    memset(&other_model, 0, sizeof(other_model));
    memset(&bad_model, 0, sizeof(bad_model));
    memset(&mismatch_model, 0, sizeof(mismatch_model));
    memset(&replacement_model, 0, sizeof(replacement_model));

    input.data = data;
    input.ndim = 1;
    input.shape[0] = 4;

    model.magic = RVAIC_MODEL_MAGIC;
    model.version = RVAIC_MODEL_VERSION;
    model.input_count = 1;
    model.output_count = 1;
    model.required_abi = RVAIC_MODEL_VERSION;
    model.required_features = RVAIC_BACKEND_CPU;
    model.target_hash = "target-good";
    model.name = "copy";
    model.run = copy_run;
    other_model = model;
    other_model.name = "other";
    bad_model = model;
    bad_model.required_abi = RVAIC_MODEL_VERSION + 1u;
    mismatch_model = model;
    mismatch_model.target_hash = "target-bad";
    replacement_model = model;

    assert(rvaic_init() == 0);
    assert(rvaic_runtime_target_hash() == 0);
    assert(rvaic_runtime_set_target_hash("") == -1);
    assert(rvaic_runtime_set_target_hash("target-good") == 0);
    assert(strcmp(rvaic_runtime_target_hash(), "target-good") == 0);
    assert(rvaic_arena_pool_init(pool, sizeof(pool)) == 0);
    assert(rvaic_arena_pool_ready() == 1);
    assert(rvaic_arena_reserve(16, 8, 1, &reservation_a) == 0);
    assert(rvaic_arena_reserve(32, 8, 1, &reservation_b) == 0);
    assert(reservation_a.offset + reservation_a.size <= reservation_b.offset || reservation_b.offset + reservation_b.size <= reservation_a.offset);
    assert(rvaic_arena_reserve_at(16, 8, 64, 1, &reservation_fixed) == 0);
    assert(rvaic_arena_reserve_at(16, 8, 72, 1, &reservation_a) == RVAIC_STATUS_NO_RESOURCE);
    assert(rvaic_arena_release(&reservation_a) == 0);
    assert(rvaic_arena_release(&reservation_b) == 0);
    assert(rvaic_arena_release(&reservation_fixed) == 0);
    assert(rvaic_arena_pool_size() == sizeof(pool));
    assert(rvaic_session_create("bad", 3) == 0);
    assert(rvaic_model_admit(&model, 0, RVAIC_BACKEND_CPU) == 0);
    assert(rvaic_model_admit(&bad_model, 0, RVAIC_BACKEND_CPU) == -1);
    assert(rvaic_model_admit(&mismatch_model, sizeof(pool), RVAIC_BACKEND_CPU) == -1);
    backend.name = "cpu";
    backend.backend_mask = RVAIC_BACKEND_CPU;
    backend.reset = backend_reset;
    assert(rvaic_backend_register(&backend) == 0);
    assert(rvaic_backend_find("cpu") != 0);
    assert(rvaic_model_register("copy", &model) == 0);
    assert(rvaic_model_find("copy") == &model);
    assert(rvaic_model_count() == 1);
    model.arena_size = 32u;
    admission[0].model_name = "copy";
    admission[0].arena_bytes = 32u;
    admission[0].alignment = 8u;
    admission[0].exclusive = 1u;
    admission[0].scope = "system_sram";
    admission[0].offset = 64u;
    admission[0].parallel_group = 1u;
    admission[1].model_name = "other";
    admission[1].arena_bytes = 16u;
    admission[1].alignment = 8u;
    admission[1].exclusive = 1u;
    admission[1].scope = "system_sram";
    admission[1].offset = 0u;
    admission[1].parallel_group = 2u;
    assert(rvaic_model_admit_contract(&model, admission, 2, rvaic_arena_pool_available(), RVAIC_BACKEND_CPU) == 0);
    admission[0].arena_bytes = 128u;
    assert(rvaic_model_admit_contract(&model, admission, 2, rvaic_arena_pool_available(), RVAIC_BACKEND_CPU) == -1);
    admission[0].arena_bytes = 32u;
    session = rvaic_session_create_with_admission(&model, sizeof(model), admission, 2, RVAIC_BACKEND_CPU);
    assert(session != 0);
    other_model.arena_size = 16u;
    parallel_session = rvaic_session_create_with_admission(&other_model, sizeof(other_model), admission, 2, RVAIC_BACKEND_CPU);
    assert(parallel_session != 0);
    assert(rvaic_arena_pool_available() == 48u);
    rvaic_session_destroy(parallel_session);
    assert(rvaic_session_create_with_admission(&model, sizeof(model), admission, 2, RVAIC_BACKEND_CPU) == 0);
    rvaic_session_destroy(session);
    serial_session = rvaic_session_create_with_admission(&model, sizeof(model), admission, 2, RVAIC_BACKEND_CPU);
    assert(serial_session != 0);
    rvaic_session_destroy(serial_session);
    session = rvaic_session_create_with_admission(&model, sizeof(model), admission, 2, RVAIC_BACKEND_CPU);
    assert(session != 0);
    session2 = rvaic_session_create(&model, sizeof(model));
    assert(session2 != 0);
    assert(rvaic_model_ref_count("copy") == 2u);
    assert(rvaic_model_register("copy", &model) == 0);
    assert(rvaic_model_register("copy", &replacement_model) == -1);
    assert(rvaic_model_unregister("copy") == -1);
    assert(rvaic_set_input(session, 0, &input) == 0);
    assert(rvaic_run(session) == 0);
    assert(rvaic_get_output(session, 0, &output) == 0);
    assert(output.data == data);
    assert(output.shape[0] == 4);
    job.session = session;
    job.inputs = &input;
    job.outputs = &output;
    job.backend_mask = RVAIC_BACKEND_CPU;
    job.fence = &fence;
    job.callback = done;
    job.user_data = &callback_seen;
    assert(rvaic_submit(&job) == 0);
    assert(rvaic_job_wait(&job, 0) == 0);
    assert(rvaic_fence_wait(&fence, 0) == 0);
    assert(callback_seen == 1);
    plans[0].name = "rvv_unverified";
    plans[0].backend_mask = RVAIC_BACKEND_RVV;
    plans[0].verified = 0u;
    plans[0].expected_latency_us = 1u;
    plans[0].evidence_level = RVAIC_EVIDENCE_E1;
    plans[0].required_evidence_level = RVAIC_EVIDENCE_E5;
    plans[1].name = "safe_cpu";
    plans[1].backend_mask = RVAIC_BACKEND_CPU;
    plans[1].verified = 1u;
    plans[1].expected_latency_us = 20u;
    plans[1].arena_bytes = 32u;
    plans[1].evidence_level = RVAIC_EVIDENCE_E3;
    plans[1].required_evidence_level = RVAIC_EVIDENCE_E3;
    plans[1].target_hash = "target-good";
    assert(rvaic_plan_admit(&plans[0], 64u, RVAIC_BACKEND_RVV, 0u, RVAIC_EVIDENCE_E3, &plan_admission) == RVAIC_STATUS_INVALID_PLAN);
    assert((plan_admission.reject_mask & RVAIC_PLAN_REJECT_UNVERIFIED) != 0u);
    assert((plan_admission.reject_mask & RVAIC_PLAN_REJECT_EVIDENCE) != 0u);
    assert(rvaic_plan_admit(&plans[1], 16u, RVAIC_BACKEND_CPU, 0u, RVAIC_EVIDENCE_E3, &plan_admission) == RVAIC_STATUS_INVALID_PLAN);
    assert((plan_admission.reject_mask & RVAIC_PLAN_REJECT_MEMORY) != 0u);
    assert(rvaic_plan_admit(&plans[1], 64u, RVAIC_BACKEND_CPU, 10u, RVAIC_EVIDENCE_E3, &plan_admission) == RVAIC_STATUS_INVALID_PLAN);
    assert((plan_admission.reject_mask & RVAIC_PLAN_REJECT_DEADLINE) != 0u);
    plans[1].target_hash = "target-bad";
    assert(rvaic_plan_admit(&plans[1], 64u, RVAIC_BACKEND_CPU, 0u, RVAIC_EVIDENCE_E3, &plan_admission) == RVAIC_STATUS_INVALID_PLAN);
    assert((plan_admission.reject_mask & RVAIC_PLAN_REJECT_TARGET) != 0u);
    assert(plan_admission.target_hash_match == 0u);
    plans[1].target_hash = "target-good";
    assert(rvaic_plan_select_with_evidence(plans, 2, 64u, RVAIC_BACKEND_CPU | RVAIC_BACKEND_RVV, 0u, RVAIC_EVIDENCE_E4, &plan_admission) == 0);
    assert((plan_admission.reject_mask & RVAIC_PLAN_REJECT_EVIDENCE) != 0u);
    assert(rvaic_plan_select(plans, 2, 64u, RVAIC_BACKEND_CPU, 0) == &plans[1]);
    plans[0].backend_mask = RVAIC_BACKEND_CPU;
    plans[0].verified = 1u;
    plans[0].evidence_level = 0u;
    plans[0].required_evidence_level = 0u;
    plans[0].arena_bytes = 0u;
    assert(rvaic_plan_select(plans, 2, 0, RVAIC_BACKEND_CPU, 0) == &plans[0]);
    memset(&fence, 0, sizeof(fence));
    assert(rvaic_plan_execute(session, &plans[1], &input, &output, &fence) == 0);
    assert(rvaic_fence_wait(&fence, 0) == 0);
    assert(rvaic_service_init() == 0);
    dep_job.session = session;
    dep_job.inputs = &input;
    dep_job.outputs = &output;
    dep_job.backend_mask = RVAIC_BACKEND_CPU;
    dep_job.priority = 99u;
    dep_job.dependency = &dep_fence;
    ready_job.session = session;
    ready_job.inputs = &input;
    ready_job.outputs = &output;
    ready_job.backend_mask = RVAIC_BACKEND_CPU;
    ready_job.priority = 1u;
    ready_job.fence = &ready_fence;
    assert(rvaic_service_submit(&dep_job) == 0);
    assert(rvaic_service_submit(&ready_job) == 0);
    assert(rvaic_service_step() == 0);
    assert(ready_job.state == RVAIC_JOB_DONE);
    assert(dep_job.state == RVAIC_JOB_PENDING);
    assert(rvaic_service_drain() == -1);
    dep_fence.signaled = 1;
    dep_fence.status = 0;
    assert(rvaic_service_drain() == 0);
    assert(dep_job.state == RVAIC_JOB_DONE);
    assert(rvaic_service_init() == 0);
    low_job.session = session;
    low_job.inputs = &input;
    low_job.outputs = &output;
    low_job.backend_mask = RVAIC_BACKEND_CPU;
    low_job.priority = 1u;
    low_job.fence = &low_fence;
    high_job.session = session;
    high_job.inputs = &input;
    high_job.outputs = &output;
    high_job.backend_mask = RVAIC_BACKEND_CPU;
    high_job.priority = 9u;
    high_job.fence = &high_fence;
    assert(rvaic_service_submit(&low_job) == 0);
    assert(rvaic_service_submit(&high_job) == 0);
    assert(rvaic_backend_queue_state(RVAIC_BACKEND_CPU, &queue_state) == 0);
    assert(queue_state.queued == 2u);
    assert(rvaic_backend_lock(RVAIC_BACKEND_CPU) == 0);
    assert(rvaic_service_step() == 0);
    assert(high_job.state == RVAIC_JOB_PENDING);
    assert(rvaic_backend_unlock(RVAIC_BACKEND_CPU) == 0);
    assert(rvaic_service_step() == 0);
    assert(high_job.state == RVAIC_JOB_DONE);
    assert(low_job.state == RVAIC_JOB_PENDING);
    assert(rvaic_service_drain() == 0);
    assert(rvaic_service_stats(&service_stats) == 0);
    assert(service_stats.completed == 2u);
    assert(rvaic_service_init() == 0);
    npu_blocked_job.session = session;
    npu_blocked_job.inputs = &input;
    npu_blocked_job.outputs = &output;
    npu_blocked_job.backend_mask = RVAIC_BACKEND_NPU;
    npu_blocked_job.priority = 99u;
    cpu_unblocked_job.session = session;
    cpu_unblocked_job.inputs = &input;
    cpu_unblocked_job.outputs = &output;
    cpu_unblocked_job.backend_mask = RVAIC_BACKEND_CPU;
    cpu_unblocked_job.priority = 1u;
    assert(rvaic_backend_lock(RVAIC_BACKEND_NPU) == 0);
    assert(rvaic_service_submit(&npu_blocked_job) == 0);
    assert(rvaic_service_submit(&cpu_unblocked_job) == 0);
    assert(rvaic_service_step() == 0);
    assert(cpu_unblocked_job.state == RVAIC_JOB_DONE);
    assert(npu_blocked_job.state == RVAIC_JOB_PENDING);
    assert(rvaic_service_init() == 0);
    npu_fallback_job.session = session;
    npu_fallback_job.inputs = &input;
    npu_fallback_job.outputs = &output;
    npu_fallback_job.backend_mask = RVAIC_BACKEND_NPU | RVAIC_BACKEND_CPU;
    npu_fallback_job.priority = 99u;
    low_job.state = 0u;
    low_job.status = 0;
    assert(rvaic_backend_lock(RVAIC_BACKEND_NPU) == 0);
    assert(rvaic_service_submit(&npu_fallback_job) == 0);
    assert(rvaic_service_submit(&low_job) == 0);
    assert(rvaic_service_step() == 0);
    assert(npu_fallback_job.state == RVAIC_JOB_DONE);
    assert(low_job.state == RVAIC_JOB_PENDING);
    assert(rvaic_backend_queue_state(RVAIC_BACKEND_NPU, &queue_state) == 0);
    assert(queue_state.queued == 0u);
    assert(queue_state.completed == 0u);
    assert(rvaic_backend_queue_state(RVAIC_BACKEND_CPU, &queue_state) == 0);
    assert(queue_state.completed == 1u);
    assert(rvaic_service_drain() == 0);
    memset(&job, 0, sizeof(job));
    memset(&fence, 0, sizeof(fence));
    job.session = session;
    job.inputs = &input;
    job.outputs = &output;
    job.backend_mask = RVAIC_BACKEND_CPU;
    job.timeout_us = 1u;
    job.fence = &fence;
    assert(rvaic_service_submit(&job) == 0);
    assert(rvaic_service_watchdog_tick(2u) == 1);
    assert(job.status == RVAIC_STATUS_TIMEOUT);
    assert(rvaic_fence_wait(&fence, 0) == RVAIC_STATUS_TIMEOUT);
    assert(backend_resets == 1);
    assert(rvaic_backend_queue_state(RVAIC_BACKEND_CPU, &queue_state) == 0);
    assert(queue_state.queued == 0u);
    memset(&job, 0, sizeof(job));
    assert(rvaic_cancel(&job) == 0);
    assert(job.status == RVAIC_STATUS_CANCELLED);
    memset(&job, 0, sizeof(job));
    job.timeout_us = 1;
    assert(rvaic_timeout_check(&job, 2) == RVAIC_STATUS_TIMEOUT);
    rvaic_session_destroy(session2);
    rvaic_session_destroy(session);
    assert(rvaic_model_ref_count("copy") == 0u);
    assert(rvaic_model_register("copy", &replacement_model) == 0);
    assert(rvaic_model_find("copy") == &replacement_model);
    assert(rvaic_model_unregister("copy") == 0);
    model.arena_size = 128u;
    assert(rvaic_session_create(&model, sizeof(model)) == 0);
    model.arena_size = 0u;
    assert(rvaic_session_create(&model, sizeof(model)) != 0);

    return 0;
}
