#!/usr/bin/env python3
"""Compose a K230 SD-card image from a verified base image plus SYSU payload."""

from __future__ import annotations

import argparse
import os
import json
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import k230_image_analyze


ROOT = Path(__file__).resolve().parents[1]


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    env.setdefault("SOURCE_DATE_EPOCH", "946684800")
    return subprocess.run(cmd, env=env, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=False)


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def copy_tree(src: Path, dst: Path) -> None:
    for item in src.rglob("*"):
        if not item.is_file():
            continue
        rel = item.relative_to(src)
        target = dst / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(item, target)


BOARD_PACKAGE_EXCLUDE_PREFIXES = (".acceptance/",)
BOARD_PACKAGE_EXCLUDE_NAMES = {"host_smoke", "host_compile.log", "host_run.log", "tvm_c_export.tar"}


def copy_board_package(src: Path, dst: Path) -> list[str]:
    copied = []
    for item in src.rglob("*"):
        if not item.is_file():
            continue
        rel = item.relative_to(src).as_posix()
        if rel.startswith(BOARD_PACKAGE_EXCLUDE_PREFIXES) or item.name in BOARD_PACKAGE_EXCLUDE_NAMES:
            continue
        target = dst / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(item, target)
        copied.append(rel)
    return sorted(copied)


def target_summary(target: Path | None) -> dict[str, Any]:
    if target is None:
        return {"present": False}
    data = load_json(target)
    return {
        "present": True,
        "path": str(target.resolve()),
        "target_hash": k230_image_analyze.digest(target),
        "name": data.get("name"),
        "isa": data.get("isa"),
        "abi": data.get("abi"),
        "cpu": data.get("cpu"),
        "board": data.get("board", {}),
        "boot": data.get("boot", {}),
        "rvv": data.get("rvv", {}),
        "npu": data.get("npu", {}),
    }


def payload_paths(root: Path) -> list[str]:
    return sorted(item.relative_to(root).as_posix() for item in root.rglob("*") if item.is_file())


def render_boot_smoke() -> str:
    return """# Generated by tools/k230_image_compose.py.
try:
    import os
except ImportError:
    os = None


def _exists(path):
    if os is None:
        return False
    try:
        os.stat(path)
        return True
    except OSError:
        return False


def _exists_any(rel):
    for root in ("/sdcard", "", "/"):
        path = (root.rstrip("/") + "/" + rel) if root else rel
        if _exists(path):
            return True
    return False


def main():
    print("SYSU_K230_IMAGE_BOOT_SMOKE_START")
    manifest_ok = _exists_any("sysu/image_manifest.json")
    plan_ok = _exists_any("sysu/board_test_plan.json")
    if manifest_ok:
        print("SYSU_K230_IMAGE_MANIFEST_PRESENT")
    else:
        print("SYSU_K230_IMAGE_MANIFEST_MISSING")
    if plan_ok:
        print("SYSU_K230_BOARD_TEST_PLAN_PRESENT")
    else:
        print("SYSU_K230_BOARD_TEST_PLAN_MISSING")
    if manifest_ok and plan_ok:
        print("SYSU_K230_IMAGE_BOOT_SMOKE_PASS")
        return True
    print("SYSU_K230_IMAGE_BOOT_SMOKE_FAIL")
    return False


if __name__ == "__main__":
    main()
"""


def denoise_vectors() -> tuple[list[float], list[float]]:
    frame = [0.0, 0.125, -0.25, 0.5, -0.375, 0.25, 0.0, -0.125, 0.375, -0.5, 0.625, -0.25, 0.125, 0.0, -0.125, 0.25]
    expected = []
    for idx, value in enumerate(frame):
        left = frame[idx - 1] if idx > 0 else value
        right = frame[idx + 1] if idx + 1 < len(frame) else value
        expected.append(round(0.25 * left + 0.5 * value + 0.25 * right, 6))
    return frame, expected


def render_audio_denoise_smoke() -> str:
    frame, expected = denoise_vectors()
    return f"""# Generated by tools/k230_image_compose.py.
FRAME = {json.dumps(frame)}
EXPECTED = {json.dumps(expected)}
EPSILON = 0.0001


def denoise(frame):
    out = []
    last = len(frame) - 1
    for idx, value in enumerate(frame):
        left = frame[idx - 1] if idx > 0 else value
        right = frame[idx + 1] if idx < last else value
        out.append(0.25 * left + 0.5 * value + 0.25 * right)
    return out


def main():
    print("SYSU_K230_AUDIO_DENOISE_START")
    got = denoise(FRAME)
    max_abs = 0.0
    for idx, value in enumerate(got):
        diff = abs(value - EXPECTED[idx])
        if diff > max_abs:
            max_abs = diff
    print("SYSU_K230_AUDIO_DENOISE_MAX_ABS:%0.6f" % max_abs)
    if max_abs <= EPSILON:
        print("SYSU_K230_AUDIO_DENOISE_DIFF_PASS")
        return True
    print("SYSU_K230_AUDIO_DENOISE_DIFF_FAIL")
    return False


if __name__ == "__main__":
    main()
"""


def render_rvaic_package_probe() -> str:
    return """# Generated by tools/k230_image_compose.py.
try:
    import os
except ImportError:
    os = None
try:
    import json
except ImportError:
    json = None


def _exists(path):
    if os is None:
        return False
    try:
        os.stat(path)
        return True
    except OSError:
        return False


def _read_text(path):
    try:
        with open(path, "r") as handle:
            return handle.read()
    except Exception:
        return ""


def _load_json(path):
    text = _read_text(path)
    if not text:
        return {}
    if json is None:
        return {"_raw": text}
    try:
        return json.loads(text)
    except Exception:
        return {"_raw": text}


def _exists_any(rel):
    for root in ("/sdcard", "", "/"):
        path = (root.rstrip("/") + "/" + rel) if root else rel
        if _exists(path):
            return True
    return False


def _first_existing(rel):
    for root in ("/sdcard", "", "/"):
        path = (root.rstrip("/") + "/" + rel) if root else rel
        if _exists(path):
            return path
    return ""


def _first_package(root):
    if os is None:
        return ""
    try:
        names = os.listdir(root)
    except Exception:
        return ""
    for name in names:
        path = root.rstrip("/") + "/" + name
        if _exists(path + "/contracts/target_contract.json") or _exists(path + "/proof_manifest.json") or _exists(path + "/evidence/proof_manifest.json"):
            return path
    return ""


def _target_hash_from_manifest():
    manifest = _first_existing("sysu/image_manifest.json")
    data = _load_json(manifest) if manifest else {}
    target = data.get("target", {}) if hasattr(data, "get") else {}
    return target.get("target_hash", "") if hasattr(target, "get") else ""


def _package_expected_from_manifest():
    manifest = _first_existing("sysu/image_manifest.json")
    data = _load_json(manifest) if manifest else {}
    package = data.get("rvaic_package", {}) if hasattr(data, "get") else {}
    return bool(package.get("source") or package.get("present")) if hasattr(package, "get") else False


def main():
    print("SYSU_K230_RVAIC_PACKAGE_PROBE_START")
    package_expected = _package_expected_from_manifest()
    package_root = _first_existing("sysu/rvaic")
    package_dir = _first_package(package_root) if package_root else ""
    proof_ok = False
    hash_ok = not package_expected
    if package_root:
        print("SYSU_K230_RVAIC_PACKAGE_ROOT_PRESENT")
    else:
        print("SYSU_K230_RVAIC_PACKAGE_ROOT_MISSING")
    if package_dir:
        print("SYSU_K230_RVAIC_PACKAGE_PRESENT")
        target_contract = package_dir + "/contracts/target_contract.json"
        proof_manifest = package_dir + "/evidence/proof_manifest.json"
        if not _exists(proof_manifest):
            proof_manifest = package_dir + "/proof_manifest.json"
        target = _load_json(target_contract)
        proof = _load_json(proof_manifest)
        if target:
            print("SYSU_K230_RVAIC_TARGET_CONTRACT_PRESENT")
        else:
            print("SYSU_K230_RVAIC_TARGET_CONTRACT_MISSING")
        if proof:
            print("SYSU_K230_RVAIC_PROOF_PASS")
            proof_ok = True
        else:
            print("SYSU_K230_RVAIC_PROOF_FAIL")
        expected_hash = _target_hash_from_manifest()
        package_hash = target.get("target_hash", "") if hasattr(target, "get") else ""
        if expected_hash and package_hash and expected_hash == package_hash:
            print("SYSU_K230_RVAIC_TARGET_HASH_PASS")
            hash_ok = True
        elif expected_hash or package_hash:
            print("SYSU_K230_RVAIC_TARGET_HASH_FAIL")
            hash_ok = False
        else:
            print("SYSU_K230_RVAIC_TARGET_HASH_UNCHECKED")
            hash_ok = not package_expected
    else:
        print("SYSU_K230_RVAIC_PACKAGE_MISSING")
        if not package_expected:
            print("SYSU_K230_RVAIC_PACKAGE_NOT_REQUIRED")
    try:
        import rvaic
        info = rvaic.info("sysu")
        print("SYSU_K230_RVAIC_MODULE_IMPORT_PASS")
        print("SYSU_K230_RVAIC_INFO:%s" % info)
    except Exception as exc:
        print("SYSU_K230_RVAIC_MODULE_IMPORT_NOT_VERIFIED:%s" % exc)
    if (not package_expected) or (package_dir and proof_ok and hash_ok):
        print("SYSU_K230_RVAIC_PACKAGE_PROBE_PASS")
        return True
    print("SYSU_K230_RVAIC_PACKAGE_PROBE_FAIL")
    return False


if __name__ == "__main__":
    main()
"""


def render_run_all() -> str:
    return """# Generated by tools/k230_image_compose.py.
from sysu import run_boot_smoke
from sysu import audio_denoise_smoke
from sysu import rvaic_package_probe


def main():
    print("SYSU_K230_RUN_ALL_START")
    print("SYSU_K230_MICROPYTHON_PASS")
    boot_ok = run_boot_smoke.main()
    audio_ok = audio_denoise_smoke.main()
    probe_ok = rvaic_package_probe.main()
    if boot_ok and audio_ok and probe_ok:
        print("SYSU_K230_RUN_ALL_PASS")
        return True
    print("SYSU_K230_RUN_ALL_FAIL")
    return False


if __name__ == "__main__":
    main()
"""


def render_root_main() -> str:
    return """# Generated by tools/k230_image_compose.py.
try:
    import sys
    if "/sdcard" not in sys.path:
        sys.path.append("/sdcard")
except Exception:
    pass

try:
    from sysu import run_all
    run_all.main()
except Exception as exc:
    print("SYSU_K230_MAIN_LAUNCH_FAIL:%s" % exc)
"""


def run_payload_host_smoke(payload: Path, *, package_expected: bool) -> dict[str, Any]:
    env = os.environ.copy()
    env["PYTHONPATH"] = str(payload)
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    command = [sys.executable, "main.py"]
    if not (payload / "main.py").exists():
        command = [sys.executable, "-c", "from sysu import run_all; raise SystemExit(0 if run_all.main() else 1)"]
    proc = subprocess.run(
        command,
        cwd=str(payload),
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    markers = {
        "SYSU_K230_MICROPYTHON_PASS": "SYSU_K230_MICROPYTHON_PASS" in proc.stdout,
        "SYSU_K230_IMAGE_BOOT_SMOKE_PASS": "SYSU_K230_IMAGE_BOOT_SMOKE_PASS" in proc.stdout,
        "SYSU_K230_AUDIO_DENOISE_DIFF_PASS": "SYSU_K230_AUDIO_DENOISE_DIFF_PASS" in proc.stdout,
        "SYSU_K230_RVAIC_PACKAGE_PROBE_PASS": "SYSU_K230_RVAIC_PACKAGE_PROBE_PASS" in proc.stdout,
        "SYSU_K230_RUN_ALL_PASS": "SYSU_K230_RUN_ALL_PASS" in proc.stdout,
    }
    if package_expected:
        markers.update(
            {
                "SYSU_K230_RVAIC_PACKAGE_PRESENT": "SYSU_K230_RVAIC_PACKAGE_PRESENT" in proc.stdout,
                "SYSU_K230_RVAIC_PROOF_PASS": "SYSU_K230_RVAIC_PROOF_PASS" in proc.stdout,
                "SYSU_K230_RVAIC_TARGET_HASH_PASS": "SYSU_K230_RVAIC_TARGET_HASH_PASS" in proc.stdout,
            }
        )
    return {
        "ok": proc.returncode == 0 and all(markers.values()),
        "returncode": proc.returncode,
        "markers": markers,
        "stdout": proc.stdout,
        "not_claimed": ["host payload smoke is not physical K230 MicroPython evidence"],
    }


def copy_package(package: Path, sysu: Path) -> dict[str, Any]:
    dst_root = sysu / "rvaic"
    dst_root.mkdir(parents=True, exist_ok=True)
    dst = dst_root / package.name
    if package.is_dir():
        copied = copy_board_package(package, dst)
    else:
        shutil.copyfile(package, dst)
        copied = [package.name]
    return {"source": str(package), "destination": str(dst.relative_to(sysu.parent).as_posix()), "files": copied}


def default_payload(
    root: Path,
    manifest: dict[str, Any],
    *,
    package: Path | None = None,
    install_main: bool = True,
) -> Path:
    payload = root / "payload"
    if payload.exists():
        shutil.rmtree(payload)
    sysu = payload / "sysu"
    sysu.mkdir(parents=True, exist_ok=True)
    (sysu / "__init__.py").write_text("# SYSU K230 payload package.\n", encoding="utf-8")
    (sysu / "run_boot_smoke.py").write_text(render_boot_smoke(), encoding="utf-8")
    (sysu / "audio_denoise_smoke.py").write_text(render_audio_denoise_smoke(), encoding="utf-8")
    (sysu / "rvaic_package_probe.py").write_text(render_rvaic_package_probe(), encoding="utf-8")
    (sysu / "run_all.py").write_text(render_run_all(), encoding="utf-8")
    if install_main:
        (payload / "main.py").write_text(render_root_main(), encoding="utf-8")
    package_info = copy_package(package.resolve(), sysu) if package else {"present": False}
    board_plan = {
        "schema": "sysuos.k230.board_test_plan.v1",
        "execution": [
            "Boot the board from this SD image.",
            "Capture the serial console.",
            "If main.py is not auto-run by the firmware, run: import sysu.run_all as run_all; run_all.main()",
        ],
        "expected_markers": [
            "SYSU_K230_MICROPYTHON_PASS",
            "SYSU_K230_IMAGE_BOOT_SMOKE_PASS",
            "SYSU_K230_AUDIO_DENOISE_DIFF_PASS",
            "SYSU_K230_RVAIC_PACKAGE_PROBE_PASS",
            "SYSU_K230_RUN_ALL_PASS",
        ],
        "not_claimed": [
            "native rvaic MicroPython module board import",
            "physical KPU/NPU acceleration",
            "self-hosted SYSU boot chain",
        ],
    }
    write_json(sysu / "board_test_plan.json", board_plan)
    manifest.update(
        {
            "payload_schema": "sysuos.k230.usable_image_payload.v1",
            "payload_entrypoints": {
                "boot_smoke": "sysu/run_boot_smoke.py",
                "audio_denoise_smoke": "sysu/audio_denoise_smoke.py",
                "rvaic_package_probe": "sysu/rvaic_package_probe.py",
                "run_all": "sysu/run_all.py",
                "root_main": "main.py" if install_main else "",
            },
            "rvaic_package": package_info,
            "board_test_plan": "sysu/board_test_plan.json",
            "payload_files": payload_paths(payload),
        }
    )
    write_json(sysu / "image_manifest.json", manifest)
    (sysu / "README.txt").write_text(
        "SYSU project payload staged on a verified CanMV-K230 base image.\n"
        "This derived image preserves the base boot chain; it is not a self-hosted SYSU boot chain yet.\n",
        encoding="utf-8",
    )
    return payload


def inject_payload(image: Path, partition: dict[str, Any], payload: Path, mount_root: Path) -> dict[str, Any]:
    del mount_root
    image_spec = f"{image}@@{partition['offset_bytes']}"
    outputs = []
    for item in sorted(payload.iterdir()):
        proc = run(["mcopy", "-m", "-i", image_spec, "-s", "-o", str(item), "::/"])
        outputs.append(proc.stdout.strip())
        if proc.returncode != 0:
            return {"ok": False, "error": proc.stdout.strip(), "item": str(item)}
    return {"ok": True, "partition_index": partition["index"], "payload": str(payload), "files": payload_paths(payload), "tool": "mcopy", "output": outputs}


def compose(
    base_image: Path,
    out: Path,
    payload: Path | None = None,
    *,
    target: Path | None = None,
    package: Path | None = None,
    install_main: bool = True,
    inject: bool = True,
    data_partition_index: int = 2,
) -> dict[str, Any]:
    out.mkdir(parents=True, exist_ok=True)
    image = out / "SYSUOS_K230_V3P0.img"
    shutil.copyfile(base_image, image)
    analysis = k230_image_analyze.analyze(image, out / "analysis")
    manifest = {
        "producer": "sysu-soc-image-factory",
        "artifact_kind": "k230_derived_sdcard_image",
        "generated_at": utc_now(),
        "base_image": str(base_image.resolve()),
        "base_image_sha256": k230_image_analyze.digest(base_image),
        "image": str(image),
        "target": target_summary(target),
        "derived_from_verified_base_image": True,
        "self_hosted_boot_chain": False,
        "boot_chain_source": "verified_official_base_image_raw_boot_region",
        "not_claimed": [
            "The raw K230 boot region is preserved from the base image.",
            "This is a bootable integration image, not a from-source SYSU system image.",
            "Board execution is not claimed until serial markers are captured from the physical board.",
        ],
    }
    generated_payload = payload is None
    payload_dir = payload.resolve() if payload else default_payload(out, manifest, package=package, install_main=install_main)
    manifest["payload_files"] = payload_paths(payload_dir)
    payload_host_smoke = run_payload_host_smoke(payload_dir, package_expected=package is not None) if install_main else {"ok": False, "skipped": True, "reason": "main launcher disabled"}
    partition = next((p for p in analysis["partitions"] if p["index"] == data_partition_index), None)
    injection = {"ok": False, "skipped": True, "reason": "payload injection disabled"}
    if inject:
        if not partition:
            injection = {"ok": False, "error": f"partition {data_partition_index} was not found"}
        else:
            injection = inject_payload(image, partition, payload_dir, out / "mnt")
    final_analysis = k230_image_analyze.analyze(image, out / "analysis_final")
    boot_before = analysis["pre_partition_boot_region"]["sha256"]
    boot_after = final_analysis["pre_partition_boot_region"]["sha256"]
    boot_region_preserved = boot_before == boot_after
    manifest.update(
        {
            "payload_dir": str(payload_dir),
            "payload_injection": injection,
            "boot_region_preserved": boot_region_preserved,
            "pre_partition_boot_region_sha256": boot_after,
            "image_sha256": k230_image_analyze.digest(image),
            "image_md5": k230_image_analyze.digest(image, "md5"),
        }
    )
    injected_files = set(injection.get("files", [])) if isinstance(injection.get("files"), list) else set()
    phase2_evidence = {
        "official_layout_analysis_pass": bool(analysis.get("ok")),
        "boot_region_preserved": boot_region_preserved,
        "payload_injection_pass": bool(not inject or injection.get("ok")),
        "root_main_present": (not install_main) or "main.py" in injected_files or not inject,
        "sysu_run_all_present": (not generated_payload) or "sysu/run_all.py" in injected_files or not inject,
        "sysu_manifest_present": (not generated_payload) or "sysu/image_manifest.json" in injected_files or not inject,
        "self_hosted_boot_chain_false": manifest["self_hosted_boot_chain"] is False,
        "payload_host_smoke_pass": (not install_main) or bool(payload_host_smoke.get("ok")),
    }
    if package is not None:
        phase2_evidence["rvaic_package_probe_host_pass"] = bool(payload_host_smoke.get("ok"))
    ok = all(phase2_evidence.values())
    write_json(
        out / "k230_image_compose_report.json",
        {
            "ok": ok,
            "phase2_evidence": phase2_evidence,
            "payload_host_smoke": payload_host_smoke,
            "manifest": manifest,
            "analysis": analysis,
            "final_analysis": final_analysis,
        },
    )
    write_json(image.with_suffix(image.suffix + ".manifest.json"), manifest)
    return {"ok": ok, "image": str(image), "manifest": str(image.with_suffix(image.suffix + ".manifest.json")), "injection": injection}


def selftest() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        base = root / "base.img"
        data = bytearray(k230_image_analyze.SECTOR * 20)
        data[510:512] = b"\x55\xaa"
        entry = bytearray(16)
        entry[4] = 0x0C
        entry[8:12] = (4).to_bytes(4, "little")
        entry[12:16] = (8).to_bytes(4, "little")
        data[446:462] = entry
        base.write_bytes(data)
        report = compose(base, root / "out", inject=False)
        assert report["ok"], report
        manifest = json.loads(Path(report["manifest"]).read_text(encoding="utf-8"))
        assert manifest["self_hosted_boot_chain"] is False
        assert manifest["payload_entrypoints"]["audio_denoise_smoke"] == "sysu/audio_denoise_smoke.py"
        assert manifest["boot_region_preserved"] is True
        assert Path(report["image"]).exists()
        payload = root / "out" / "payload"
        assert (payload / "sysu" / "run_all.py").exists()
        assert "SYSU_K230_AUDIO_DENOISE_DIFF_PASS" in (payload / "sysu" / "audio_denoise_smoke.py").read_text(encoding="utf-8")
        assert json.loads((root / "out" / "k230_image_compose_report.json").read_text(encoding="utf-8"))["phase2_evidence"]["self_hosted_boot_chain_false"]
        target = root / "target.json"
        write_json(target, {"name": "test-k230", "isa": "rv64gcv", "abi": "lp64d"})
        package = root / "audio_fir_denoiser.rvaic"
        (package / "contracts").mkdir(parents=True)
        (package / "evidence").mkdir()
        (package / ".acceptance").mkdir()
        write_json(package / "contracts" / "target_contract.json", {"target_hash": k230_image_analyze.digest(target)})
        write_json(package / "evidence" / "proof_manifest.json", {"ok": True})
        (package / ".acceptance" / "host_run.log").write_text("host only\n", encoding="utf-8")
        packaged = compose(base, root / "with_package", target=target, package=package, inject=False)
        assert packaged["ok"], packaged
        packaged_report = json.loads((root / "with_package" / "k230_image_compose_report.json").read_text(encoding="utf-8"))
        markers = packaged_report["payload_host_smoke"]["markers"]
        assert markers["SYSU_K230_RVAIC_PACKAGE_PRESENT"], markers
        assert markers["SYSU_K230_RVAIC_PROOF_PASS"], markers
        assert markers["SYSU_K230_RVAIC_TARGET_HASH_PASS"], markers
        copied = packaged_report["manifest"]["rvaic_package"]["files"]
        assert ".acceptance/host_run.log" not in copied, copied

        deterministic_base = root / "deterministic.img"
        deterministic_base.write_bytes(b"\0" * (512 * 8192))
        with deterministic_base.open("r+b") as handle:
            handle.seek(510)
            handle.write(b"\x55\xaa")
            for offset, kind, start, sectors in ((446, 0x83, 64, 512), (462, 0x0C, 2048, 4096)):
                handle.seek(offset + 4)
                handle.write(bytes((kind,)))
                handle.seek(offset + 8)
                handle.write(start.to_bytes(4, "little") + sectors.to_bytes(4, "little"))
        run(["mformat", "-i", f"{deterministic_base}@@{2048 * 512}", "::"])
        overlay = root / "overlay"
        overlay.mkdir()
        (overlay / "test.py").write_text("print('test')\n", encoding="utf-8")
        first = compose(deterministic_base, root / "deterministic_a", overlay, install_main=False)
        second = compose(deterministic_base, root / "deterministic_b", overlay, install_main=False)
        assert first["ok"] and second["ok"]
        assert k230_image_analyze.digest(Path(first["image"])) == k230_image_analyze.digest(Path(second["image"]))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-image")
    parser.add_argument("--payload")
    parser.add_argument("--target", default=str(ROOT / "platforms/canaan_k230/target.json"))
    parser.add_argument("--package", help="optional generated .rvaic package to stage under sysu/rvaic/")
    parser.add_argument("--out", default=str(ROOT / "build/k230_project_image"))
    parser.add_argument("--data-partition-index", type=int, default=2)
    parser.add_argument("--no-main-launcher", action="store_true", help="do not install root main.py launcher")
    parser.add_argument("--no-inject", action="store_true")
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()
    if args.selftest:
        selftest()
        print("ok")
        return 0
    if not args.base_image:
        parser.error("--base-image is required unless --selftest is used")
    report = compose(
        Path(args.base_image).resolve(),
        Path(args.out).resolve(),
        Path(args.payload).resolve() if args.payload else None,
        target=Path(args.target).resolve() if args.target else None,
        package=Path(args.package).resolve() if args.package else None,
        install_main=not args.no_main_launcher,
        inject=not args.no_inject,
        data_partition_index=int(args.data_partition_index),
    )
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
