#!/usr/bin/env python3
"""Report reusable upstream anchors for each ADAM chip engineering step."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]

STEP_ANCHORS = {
    "model_acceptance": ["onnx", "tvm", "NNSmith"],
    "tvm_compile_package": ["tvm", "RT-AK", "ExecuTorch"],
    "rvaic_runtime": ["rt-thread", "tflite-micro", "Linux dma_fence"],
    "driver_generation": [
        "driver_reuse",
        "rt-thread",
        "kendryte-standalone-sdk",
        "NMSIS",
        "TinyUSB",
        "Wujian100 open",
        "Linux RISC-V mainline",
        "Linux ARM mainline",
        "TamaGo",
    ],
    "rtthread_scons": ["rt-thread", "RT-AK"],
    "finsh_micropython": ["rt-thread", "rtthread-micropython"],
    "rvv_npu_planning": ["tvm", "MATCH", "QiMeng-GEMM", "QiMeng-TensorOp"],
    "feedback_loop": ["tvm", "Linux DRM scheduler", "QiMeng-SALV", "QiMeng-MuPa"],
    "toolchain_and_simulation": [
        "renode_portable",
        "cppcheck",
        "riscv-tests",
        "mlperf-tiny",
        "llvm-project",
        "riscv-gnu-toolchain",
        "renode",
        "onnxruntime",
    ],
}

REFERENCE_ONLY = {
    "RT-AK": "model deployment pattern; do not vendor unless plugin compatibility is needed",
    "ExecuTorch": "AOT delegate contract reference; not a target runtime dependency",
    "Linux dma_fence": "fence semantics reference; not portable source for RT-Thread",
    "Linux DRM scheduler": "queue/timeout/reset semantics reference; not portable source for RT-Thread",
    "MATCH": "hardware-model-driven TVM mapping reference",
    "NNSmith": "differential model generation reference",
    "TinyUSB": "USB stack and BSP corpus for USB-capable targets; fetch deferred tinyusb before adapting source",
    "Wujian100 open": "RISC-V MCU peripheral driver corpus; use after license and register-semantics checks",
    "Linux RISC-V mainline": "CLINT/PLIC/SBI/DTS semantics reference; do not port Linux driver source directly",
    "Linux ARM mainline": "Device Tree binding and driver model reference for ARM SoCs; not RT-Thread source",
    "TamaGo": "bare-metal ARM/RISC-V driver architecture reference; not a C RT-Thread source dependency",
}


def manifest_items(root: Path) -> dict[str, dict[str, Any]]:
    manifest = json.loads((root / "third_party.manifest.json").read_text(encoding="utf-8"))
    items = {
        item["name"]: {**item, "group": group}
        for group, items in manifest.items()
        for item in items
    }
    items["driver_reuse"] = {
        "name": "driver_reuse",
        "url": "generated by tools/github_driver_reuse.py",
        "checks": ["driver_reuse_index.json"],
        "group": "generated",
        "use": "closest upstream driver corpus copied from GitHub/local checkouts",
    }
    return items


def local_status(root: Path, item: dict[str, Any]) -> dict[str, Any]:
    path = root / "third_party" / item["name"]
    checks = item.get("checks", [])
    executables = item.get("executables", [])
    missing_checks = [rel for rel in checks if not (path / rel).exists()]
    missing_executables = [
        rel for rel in executables if not (path / rel).exists() and shutil.which(str(path / rel)) is None
    ]
    fetched = (path / ".git").is_dir() or (path / ".fetched").is_file()
    present = path.exists() and (fetched or not missing_checks)
    usable = present and not missing_checks and not missing_executables
    commit = ""
    if (path / ".git").exists():
        proc = subprocess.run(
            ["git", "-C", str(path), "rev-parse", "--short=12", "HEAD"],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        commit = proc.stdout.strip() if proc.returncode == 0 else ""
    return {
        "name": item["name"],
        "mode": "dependency",
        "group": item.get("group"),
        "url": item.get("url"),
        "path": str(path),
        "commit": commit,
        "present": present,
        "usable": usable,
        "missing_checks": missing_checks,
        "missing_executables": missing_executables,
        "use": item.get("use", ""),
    }


def scan(root: Path = ROOT) -> dict[str, Any]:
    items = manifest_items(root)
    steps = []
    referenced = set()
    for step, anchors in STEP_ANCHORS.items():
        projects = []
        for name in anchors:
            referenced.add(name)
            if name in items:
                projects.append(local_status(root, items[name]))
            else:
                projects.append(
                    {
                        "name": name,
                        "mode": "reference",
                        "present": True,
                        "usable": True,
                        "note": REFERENCE_ONLY.get(name, "reference-only upstream idea"),
                    }
                )
        missing = [item["name"] for item in projects if item["mode"] == "dependency" and not item["usable"]]
        steps.append({"step": step, "reuse_projects": projects, "ok": not missing, "missing": missing})
    third_party = root / "third_party"
    local_dirs = {path.name for path in third_party.iterdir() if path.is_dir()} if third_party.exists() else set()
    known = set(items) | set(REFERENCE_ONLY)
    return {
        "ok": all(step["ok"] for step in steps),
        "rule": "reuse local dependencies when usable; reference-only projects inform contracts but are not vendored",
        "local_unreferenced": sorted(local_dirs - known - referenced),
        "steps": steps,
    }


def selftest() -> None:
    report = scan(ROOT)
    assert report["steps"]
    assert any(step["step"] == "rvaic_runtime" for step in report["steps"])
    assert any(step["step"] == "driver_generation" for step in report["steps"])
    runtime = next(step for step in report["steps"] if step["step"] == "rvaic_runtime")
    assert {item["name"] for item in runtime["reuse_projects"]} >= {"rt-thread", "tflite-micro", "Linux dma_fence"}
    drivers = next(step for step in report["steps"] if step["step"] == "driver_generation")
    assert {item["name"] for item in drivers["reuse_projects"]} >= {"TinyUSB", "Wujian100 open", "Linux RISC-V mainline"}
    tools = next(step for step in report["steps"] if step["step"] == "toolchain_and_simulation")
    assert {item["name"] for item in tools["reuse_projects"]} >= {"renode_portable", "cppcheck", "mlperf-tiny"}
    assert "local_unreferenced" in report


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=str(ROOT))
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()
    if args.selftest:
        selftest()
        print("ok")
        return 0
    report = scan(Path(args.root).resolve())
    print(json.dumps(report, indent=2))
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
